#!/bin/bash

# Create the documentation
#
# We will be in the root directory of a just-built distribution
# when called normally.
#

(
cd doc

if [ -f makefile -o -f Makefile ]; then
	make install
fi

for f in *.txt
do
	mwtext -t text $f > ../dist/doc/$f
done

# Use the actual options help file.
cp ../resources/help/en/options ../dist/doc/options.txt

DOC=~steve/www/web/mkgmap/content/doc
WEB_DOC_PDF=~steve/www/mkgmap.org.uk/docroot/doc/pdf
mkdir -p $WEB_DOC_PDF
cp *.txt $DOC
cp styles/style-manual.pdf $WEB_DOC_PDF
)
